# Generated by Django 4.2.6 on 2023-10-26 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('ID_Cat', models.AutoField(primary_key=True, serialize=False)),
                ('Cat_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ingredient',
            fields=[
                ('ID_ing', models.AutoField(primary_key=True, serialize=False)),
                ('Ing_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='produit',
            fields=[
                ('ID_prd', models.AutoField(primary_key=True, serialize=False)),
                ('Prd_Name', models.CharField(max_length=50)),
                ('Price', models.FloatField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.category')),
                ('ingds', models.ManyToManyField(related_name='produits', to='produit.ingredient')),
            ],
        ),
    ]
